openapi: 3.1.0
info:
  title: Meta Ads GPT Connector
  version: '1.0.0'
  description: API connector for Meta Ads GPT

servers:
  - url: https://61de-20-192-21-50.ngrok-free.app

paths:
  /query:
    post:
      operationId: queryMetaAds    # <--- REQUIRED
      summary: Query Meta Ads data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                adAccountId:
                  type: string
                question:
                  type: string
      responses:
        '200':
          description: Meta Ads Query Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  spend:
                    type: string
                  since:
                    type: string
                  until:
                    type: string
                  message:
                    type: string
